#ifndef STYLE_GAMEDEFAULTS__
    #define STYLE_GAMEDEFAULTS__ 1

    #define FONT_DEFAULT            0
    #define FONT_NORMAL			    1
    #define FONT_BIG			    2
    #define FONT_SMALL			    3
    #define FONT_BOLD			    4
    #define FONT_CONSOLE		    5
    #define FONT_OBJECTIVE		    6
        
    #define ALIGN_LEGACY_LEFT		0
    #define ALIGN_LEGACY_CENTER	    1
    #define ALIGN_LEGACY_RIGHT		2
    #define ALIGN_TOP_LEFT			4
    #define ALIGN_TOP_CENTER		5
    #define ALIGN_TOP_RIGHT		    6
    #define ALIGN_MIDDLE_LEFT		8
    #define ALIGN_MIDDLE_CENTER	    9
    #define ALIGN_MIDDLE_RIGHT		10
    #define ALIGN_BOTTOM_LEFT		12
    #define ALIGN_BOTTOM_CENTER	    13
    #define ALIGN_BOTTOM_RIGHT		14

#endif